### ISSUE TITLE
Issue with generated SQL with foreign key for MySQL

### ISSUE THREAD

**Issue by minhl** [Vanderhoof/PyDBML#23]
There seems to be issues with generated SQL when there are foreign keys. The foreign key is generated as part of the table definition, which causes error if the tables are not generated in the correct order. This can be avoid by excluding all the foreign keys in the table definition. After all the tables have been created, then create foreign keys using alter table add foreign key. See example from the dbml2sql CLI generated sql. The environment is Windows and MySQL database.

**Comment by Vanderhoof** [comment]
Good point, thank you for reporting! I'll come up with as fix soon

**Comment by Vanderhoof** [comment]
Ok, so I took a closer look at the issue and it revealed a bit of difference in how `dbml2sql` and PyDBML treats the references:

`dbml2sql` always converts references into an `ALTER TABLE` clause, which is a safe choice, but lacks the flexibility: you won't be able to generate inline references (`FOREIGN KEY` inside table definition) even if you wanted to.

PyDBML in contrast treats references as inline when they are defined inside Table definition in DBML, and as `ALTER TABLE` if they are defined outside the table as `Ref: table1.col1 > table2.col2`.

In my opinion we have to leave the choice to the user, so that they can decide if they want the references to be rendered as inline or not. So the user has to be aware that if they reference the table that was not yet defined, it will result in the error you mentioned. This is the way PyDBML works now and to me it looks like the correct, explicit way.

To avoid the error of referencing not yet defined tables, either use inline reference to a table after its definition, or use standalone references.

An example:

```
Table books {
  id integer [pk]
  author_id integer [ref: > authors.id] // this is wrong, table "authors" is not yet defined
}

Table authors {
  id integer
  name varchar
}
```

This will generate SQL, but it won't work, because we are referencing a not existing table. 

Instead write:

```
Table authors {
  id integer
  name varchar
}

Table books {
  id integer [pk]
  author_id integer [ref: > authors.id]
}
```

Or write:

```
Table books {
  id integer [pk]
  author_id integer
}

Table authors {
  id integer
  name varchar
}

Ref: books.author_id > authors.id
```

**Comment by minhl** [comment]
@Vanderhoof ,
Thanks for taking the time to investigate the issue and explain how it works. I agree with your decision of keeping the way PyDBML works currently. In the future, if PyDBML can keep track of the dependencies and generate the sql in the right order, that would be a bonus. Regards.

**Comment by Vanderhoof** [comment]
@minhl that's a neat idea and shouldn't be hard to implement! It won't aid the rare case when two tables reference each other, but will work in most use cases. I'll add it to the todo-list

**Comment by Vanderhoof** [comment]
Added reordering in [1.0.4](https://github.com/Vanderhoof/PyDBML/releases/tag/1.0.4)
